### ISSUE TITLE
Long videos names are failing on iOS 12.5.2

### ISSUE THREAD

**Issue by bactn** [Cyklet/VidLoader#33]
When I tried to download a video on iOS 12.5.2. It couldn't download. But with the same video still can download on other versions (11,13,14). Other videos still can download on iOS 12.5.2. The bug only happens on some special video.
When I tried to debug. It shows `Error Domain=AVFoundationErrorDomain Code=-11800 `. It couldn't know the detailed cause. Please help me.

**Download URL:**
 `https://www2.uliza.jp/IF/iphone/iPhonePlaylist.m3u8?v=226046-957763&p=6141&d=629&n=1698&t=2e86b9693ba755c64d3edf71b16a82d7&previewflag=0&logging=1`

**Error log:**
```
2021-05-17 09:40:54:799 [Debug] [BODNetworkService.swift] : 41 sendRequest(_:) -> {"status":200,"response_code":1,"data":{"download_url":"https://www2.uliza.jp/IF/iphone/iPhonePlaylist.m3u8?v=226046-957763&p=6141&d=629&n=1698&t=2e86b9693ba755c64d3edf71b16a82d7&previewflag=0&logging=1","download_play_limit":7}}
2021-05-17 09:40:54:800 [Debug] [BODNetworkService.swift] : 42 sendRequest(_:) -> 🔴🔴🔴🔴🔴🔴--------------------------------END  nil------------------------------------------
2021-05-17 09:40:59.735294+0700 [741:133600] Task <C5716F46-6FF5-407D-97C5-72D4B272532A>.<3> load failed with error Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSLocalizedDescription=The operation could not be completed, _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundAVAssetDownloadTask <C5716F46-6FF5-407D-97C5-72D4B272532A>.<3>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "BackgroundAVAssetDownloadTask <C5716F46-6FF5-407D-97C5-72D4B272532A>.<3>"
), NSLocalizedFailureReason=An unknown error occurred (63)} [-11800]
2021-05-17 09:40:59:741 [Debug] [BODRealmManager.swift] : 71 episodeDLInfo(saveDlInfo:intoEpisodeId:) -> Saved episode 226046 at: Optional(2021-05-17 02:40:54 +0000)
2021-05-17 09:40:59:744 [Debug] [DownloadIndicatorButton.swift] : 213 setupDownloadButton(with:episode:) -> 
====>
error: custom(.VidLoaderError(code: -11800, description: "Error Domain=AVFoundationErrorDomain Code=-11800 \"The operation could not be completed\" UserInfo={NSLocalizedDescription=The operation could not be completed, _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundAVAssetDownloadTask <C5716F46-6FF5-407D-97C5-72D4B272532A>.<3>, _NSURLErrorRelatedURLSessionTaskErrorKey=(\n    \"BackgroundAVAssetDownloadTask <C5716F46-6FF5-407D-97C5-72D4B272532A>.<3>\"\n), NSLocalizedFailureReason=An unknown error occurred (63)}", localizedDescription: "The operation could not be completed", domain: "AVFoundationErrorDomain"))
<====
2021-05-17 09:40:59:748 [Debug] [DownloadIndicatorButton.swift] : 213 setupDownloadButton(with:episode:) -> 
====>
error: custom(VidLoaderError(code: -11800, description: "Error Domain=AVFoundationErrorDomain Code=-11800 \"The operation could not be completed\" UserInfo={NSLocalizedDescription=The operation could not be completed, _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundAVAssetDownloadTask <C5716F46-6FF5-407D-97C5-72D4B272532A>.<3>, _NSURLErrorRelatedURLSessionTaskErrorKey=(\n    \"BackgroundAVAssetDownloadTask <C5716F46-6FF5-407D-97C5-72D4B272532A>.<3>\"\n), NSLocalizedFailureReason=An unknown error occurred (63)}", localizedDescription: "The operation could not be completed", domain: "AVFoundationErrorDomain"))
<====
```

**Comment by Cyklet** [comment]
Hi @bactn can you please provide a valid URL, I will try to reproduce it on my side

**Comment by bactn** [comment]
@Cyklet 
This is an error URL, please check it. Thanks
https://www2.uliza.jp/IF/iphone/iPhonePlaylist.m3u8?v=227483-962430&p=6141&d=629&n=1698&t=7dec94a54284a10e8560d75430c40538&previewflag=0&logging=1

**Comment by Cyklet** [comment]
Hi @bactn I have tried on few phones with ios 14 and 13 (all links did work), sadly I don't have a phone with ios 12 at the moment.
It sounds like an iOS update issue (works on all versions and only 12.5.2 not, previously happened few times after Apple updates).
I have checked the wiki `https://en.wikipedia.org/wiki/IOS_12` and apple pushed a new update 12.5.3 on May 3, 2021 (often when they touch smth. they can break over old iOS parts), maybe it is fixed in the new version, also try to restart the phone maybe AVFoundation will reset and it will help.

**Comment by bactn** [comment]
Hi @Cyklet 
I checked with my co-worker on ios 12.5.3. But this bug still happens on it. I also tried to restart the phone but nothing change. The bug doesn't occur on all videos, only some videos(10-15videos).

**Comment by Cyklet** [comment]
I am trying to get an iPhone with iOS 12 but without success, when I will have it in my hands I will be able to check what is happening with downloader.

**Comment by bactn** [comment]
@Cyklet thanks you for your supporting, I'm checking but haven't found the cause yet.

**Comment by bactn** [comment]
@Cyklet 
When I checked to download with Apple HLS Download example, It was successful, I will continue to investigate the cause
https://developer.apple.com/documentation/avfoundation/media_playback_and_selection/using_avfoundation_to_play_and_persist_http_live_streams

**Comment by bactn** [comment]
Follow this link, Do I need to add CODECS to the m3u8 file?
https://developer.apple.com/forums/thread/121097

**Comment by tridorje** [comment]
@Cyklet 
Hi Petre, if you have time, can you access my computer by TeamViewer,
I will reproduce this error.

**Comment by Cyklet** [comment]
Hi, sorry for the late response

@bactn `Follow this link, Do I need to add CODECS to the m3u8 file` - you can try to add codes, but it may not change anything, it looks like a strange iOS thingy.

@tridorje I am not sure if I have time for TeamViewer in the next few weeks, I am starting a new job and I barely have some free time, but I still hope that I will get my hand on a phone that has iOS 12.

@bactn
`When I checked to download with Apple HLS Download example, It was successful` - this is a good start point, usually, if apple example works it means that it may be something wrong with encryption keys, apple don't save them in their examples.
You can try to do next things:
- when starting download try to send DownloadValues only with URL id and a simple title, sometimes because of some chars in the title or large artwork AVFoundation may not start download
- try to set up local framework so you will be able to use breakpoints (cocoapods -> pod 'VidLoader', :path => '..../VidLoader/VidLoader.podspec')and check after each step when download is failing. 
- try to disable the encryption key download step (in ResourceLoader -> shouldWaitForLoadingOfRequestedResource -> return false should skip the download encryption logic flow), if you bypass this step and download succeed then check why `shouldWaitForLoadingOfRequestedResource` code is not working with your files in iOS 12. - the issue may be in this method, when AVDownloadSession calls delegate our framework tries to parse m3u8 files - fin keys and then save them locally.

**Comment by Cyklet** [comment]
After investigation, we found out that for iOS 12.5.2 and only this version:
>  **if a video title is too long, the download will fail with a generic error from the AVFoundation side. (Our assumption - the title is used in the settings for application size and iOS 12.5.2 OR AVFoundation can't handle long strings)**

The fix was to truncate the video name for iOS 12.5.2 and it was done on the dev side, as iOS 12.5.2 it's not used very often, SDK will not have an update for this issue.
